default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: 
  password:

production:
  database: educoding_production

development:
  <<: *default
  database: educoding_development

test: &test
  <<: *default
  database: educoding_test

cucumber:
  <<: *test